version: '2'

services:

  db:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - db_data:/foo
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - project-network-net

  server:
    build: /server
    ports: 
      - '5050:5050'
    networks:
      - project-network-net

  client:
    build: /client
    ports: 
      - '4173:4173'
    networks:
      - project-network-net

volumes:
  db_data:

networks:
  project-network-net:
