version: '1'

services:

  db:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017" # port forward to 27018 for local development
    volumes:
      - db_data:/foo
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - project-network-net

volumes:
  db_data:

networks:
  project-network-net:
